version: '3.7'

services:
  forum:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - EXPOSE_PORT=$EXPOSE_PORT
        - APP_MODE=$APP_MODE
    container_name: ${CONTAINER_NAME}
    ports:
      - ${CONTAINER_PORTS}
    expose:
      - ${EXPOSE_PORT}:${EXPOSE_PORT}
    volumes:
      - .:/opt/app
    tty: true
