version: '3.7'

services:
  forum:
    build: .
    container_name: vue3forum
    # image: node:lts
    # working_dir: /var/www/html/app/
    entrypoint: /bin/bash
    expose:
      - 8000
    volumes:
      - .:/app
    tty: true
